### ISSUE TITLE
Conversion to-do's

### ISSUE THREAD

**Issue by darcymason** [darcymason/egsnrc2py#22]
From hand edits, keeping notes on some improvements noted for auto-transpiling:

- [ ] fix conversion of macros that were made completely blank, e.g. $PARTICLE-SELECTION-...
- [ ] check LHS of assignments for `common` block variables, and put in the common block name
- [ ] in parsing macro files, skip /*  ...  */ lines (like second $COMPUTE-RANGE that was commented out)
- [ ] try to put minus one "_m1" variables in for common block array indices
